spring:
  application:
    name: accounting-classifier

  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:postgresql://localhost:5432/oncomm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 운영 시에는 validate / none 권장
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  jackson:
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
      file-size-threshold: 1MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Swagger/OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  packages-to-scan: com.oncomm.oncomm.controller

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.oncomm.oncomm: DEBUG

# 서버 기본 포트
server:
  port: 8080


